/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa.pkg2.Personaje;

import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class AdivinaQuien extends javax.swing.JFrame {

    /**
     * Creates new form AdivinaQuien
     */
    public AdivinaQuien() {
        initComponents();
        pregunta.setText("¿Tu personaje es ficticio?");
    }
        int RadSi = 0;
        int RadNo = 0;
        int aux = 0;
        int aux2 = 0;
        int aux3 = 0;
        int aux4 = 0;
        int aux5 = 0;
        int aux6 = 0;
        int aux7 = 0;

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        RadioSi = new javax.swing.JRadioButton();
        RadioNo = new javax.swing.JRadioButton();
        Siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Programa 2 - Adivinar personaje"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Piensa en un personaje");

        pregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pregunta.setText("¿Pregunta 1?");

        buttonGroup1.add(RadioSi);
        RadioSi.setText("Sí");
        RadioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioSiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioNo);
        RadioNo.setText("No");
        RadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNoActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente >>");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RadioNo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(RadioSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Siguiente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(363, 363, 363))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pregunta)
                .addGap(27, 27, 27)
                .addComponent(RadioSi)
                .addGap(18, 18, 18)
                .addComponent(RadioNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Siguiente)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNoActionPerformed

    private void RadioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioSiActionPerformed
    }//GEN-LAST:event_RadioSiActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
 
        //Primera pregunta
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 0 && aux == 0 && aux2 == 0){
            pregunta.setText("¿Tu personaje es masculino?");
            aux++;
            buttonGroup1.clearSelection();
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 0 && aux == 0 && aux2 == 0){
            pregunta.setText("¿Tu personaje es mujer y se dedica a hacer contenido en redes sociales?");
            aux2++;
            buttonGroup1.clearSelection();
        }

        
        //Si el personaje es ficticio >>//
        //Si no es masculino >>//
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 0 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje pertenece a un anime llamado 'Cyberpunk'?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 1 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Lucyna Kushinada");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 1 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es una superheroína?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 2 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Wanda Maximoff");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 2 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Mamá Coco");
            System.exit(0);            
        }
        //<< Si no es masculino//
        
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 0 && aux == 1 && aux2 == 0 && aux4 == 0){
            pregunta.setText("¿Tu personaje nació gracias a un videojuego?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 0 && aux == 1 && aux2 == 0 && aux4 == 0){
            pregunta.setText("¿Tu personaje es protagonista del juego 'God of War'?");
            aux4++;
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 0 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Kratos");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 0 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje es del juego llamado 'Blasphemous'?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 1 && aux == 1 && aux2 == 0 && aux4 == 1 && aux3 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es el penitente");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 1 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje pertenece a Mario Bros?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje usa una gorra con su inicial?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioNo.isSelected() && RadSi == 3 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Yoshi");
            System.exit(0);   
        }
        if(RadioSi.isSelected() && RadSi == 3 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje viste con traje amarillo?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 4 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Wario");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 4 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Mario");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje es de un juego que aparece en caso de interrupción de internet?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es el dinosaurio de google");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje es de la saga de 'Assassin's Creed'?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 4 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje Etzio");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 4 && aux == 1 && aux2 == 0 && aux4 == 1){
            pregunta.setText("¿Tu personaje es un erizo?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 5 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje Sonic");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 5 && aux == 1 && aux2 == 0 && aux4 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje Leon S. Kennedy");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 0 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es originario de algún anime?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 1 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje pertenece a Dragon Ball?");
            RadSi++;
            aux3++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 1 && aux == 1 && aux2 == 0 && aux4 == 0){
            pregunta.setText("¿Tu personaje es el protagonista?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 3 && RadNo == 1 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Goku");
            System.exit(0);   
        }
        if(RadioNo.isSelected() && RadSi == 3 && RadNo == 1 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Gohan");
            System.exit(0);
        }        
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 1 && aux == 1 && aux2 == 0 && aux4 == 0){
            pregunta.setText("¿Tu personaje usa una armadura de un pegaso?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux3 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Seiya");
            System.exit(0);            
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux3 == 1){
            pregunta.setText("¿Tu personaje es reconocido por usar un sombrero de paja?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux3 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Luffy");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux3 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Naruto");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 1 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje pertenece a un comic?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 2 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje vive en Ciudad Gótica?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux3 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Batman");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 2 && aux == 1 && aux2 == 0 && aux3 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Spiderman");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 2 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es un demonio?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 3 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje se conoce como el Señor de las moscas?");
            RadSi++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux3 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Belcebú");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 3 && aux == 1 && aux2 == 0 && aux3 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Lucífugo");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 3 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es de una pelicula de Disney?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 4 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje quiere ser músico?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 4 && aux == 1 && aux2 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Miguel");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 4 && aux == 1 && aux2 == 0 && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Bambi");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 4 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es de Nickelodeon?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 5 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje toca el clarinete?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 5 && aux == 1 && aux2 == 0  && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Calamardo");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 5 && aux == 1 && aux2 == 0  && aux4 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Cosmo");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 5 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje es un doctor?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 6 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es el Dr. Simi");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 6 && aux == 1 && aux2 == 0){
            pregunta.setText("¿Tu personaje come galletas?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 7 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es el Monstruo Comegalletas");
            System.exit(0);
        }       
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 7 && aux == 1 && aux2 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es el Tigre Toño");
            System.exit(0);
        }
        //<< Si el personaje es ficticio //
        
        //Si el personaje es real >> //
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 0 && aux == 0 && aux2 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es el Karley Ruíz");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 0 && aux == 0 && aux2 == 1){
            pregunta.setText("¿Tu personaje es un perrito?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 1 && aux == 0 && aux2 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Cheems");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 1 && aux == 0 && aux2 == 1){
            pregunta.setText("¿Tu personaje sigue con vida?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 0){
            pregunta.setText("¿Tu personaje es méxicano?");
            RadSi++;
            aux6++;
            buttonGroup1.clearSelection();
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1){
            pregunta.setText("¿Tu personaje es futbolista?");
            RadNo++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1){
            pregunta.setText("¿Tu personaje es Argentino?");
            RadSi++;
            buttonGroup1.clearSelection();                        
        }        
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Cristiano Ronaldo");
            System.exit(0);
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Messi");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1){
            pregunta.setText("¿Tu personaje es Youtuber y empresario estadounidense?");
            RadNo++;
            buttonGroup1.clearSelection();                        
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux6 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Mr. Beast");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux6 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Triple H");
            System.exit(0);
        }

        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1){
            pregunta.setText("¿Tu personaje es cantante?");
            RadSi++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1){
            pregunta.setText("¿Tu personaje creó la canción 'Será que no me amas'?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 3 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Luis Miguel");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 3 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Junior H");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 2 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 0){
            pregunta.setText("¿Tu personaje debe su fama a los deportes?");
            aux7++;
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            pregunta.setText("¿Tu personaje es automovilista?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 3 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Checo Pérez");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 3 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Chicharito");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            pregunta.setText("¿Tu personaje fue electo presidente?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 2 && RadNo == 4 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Amlo");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 2 && RadNo == 4 && aux == 0 && aux2 == 1 && aux6 == 1 && aux7 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Franco Escamilla");
            System.exit(0);
        }        
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 2 && aux == 0 && aux2 == 1){
            pregunta.setText("¿Tu personaje fue político?");
            RadNo++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 3 && aux == 0 && aux2 == 1){
            pregunta.setText("¿Tu personaje fue un militar y estadista francés?");
            RadSi++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Napoleón Bonaparte");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 3 && aux == 0 && aux2 == 1 && aux6 == 0){
            pregunta.setText("¿Tu personaje fue un dictador alemán?");
            RadNo++;
            buttonGroup1.clearSelection();            
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 0 && aux6 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Hitler");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 0 && aux6 == 0){
            JOptionPane.showMessageDialog(null, "Tu personaje es Colosio");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 3 && aux == 0 && aux2 == 1 && aux5 == 0){
            pregunta.setText("¿Tu personaje fue cantante y compositor?");
            RadNo++;
            aux5++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 1){
            pregunta.setText("¿Tu personaje fue vocalista de Queen?");
            RadSi++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Freddie Mercury");
            System.exit(0);
        }        
        if(RadioNo.isSelected() && RadSi == 1 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Michael Jackson");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 4 && aux == 0 && aux2 == 1 && aux5 == 1){
            pregunta.setText("¿Tu personaje fue polímata?");
            RadNo++;
            buttonGroup1.clearSelection();
        }
        if(RadioSi.isSelected() && RadSi == 0 && RadNo == 5 && aux == 0 && aux2 == 1 && aux5 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Leonardo Da Vinci");
            System.exit(0);
        }
        if(RadioNo.isSelected() && RadSi == 0 && RadNo == 5 && aux == 0 && aux2 == 1 && aux5 == 1){
            JOptionPane.showMessageDialog(null, "Tu personaje es Juan Escutia");
            System.exit(0);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdivinaQuien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdivinaQuien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdivinaQuien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdivinaQuien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdivinaQuien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioNo;
    private javax.swing.JRadioButton RadioSi;
    private javax.swing.JButton Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pregunta;
    // End of variables declaration//GEN-END:variables
}
